### PR TITLE
Arm Reach Visualization and THREE.js setup

### PR DESCRIPTION
**Pull request by KaviMD**
Merge arm reach visualization changes into the master branch.

### CODE REVIEW

**Comment by KaviMD** [comment]
Most of the merge here is pretty simple, the big updates just have to be made to `operator_ui_regions.js`, because none of the three.js code is object-oriented.

I'm working on transitioning the current `Overlay` class to a parent class, and then creating child `OverlaySVG` and `OverlayTHREE` classes so that both svg regions and threejs scenes integrate well with the `VideoControl` system. I also switched the classes over to [ES6 class syntax](http://es6-features.org/#ClassDefinition) for cleanliness.

**Comment by KaviMD** [comment]
@mayacakmak Everything should be merged into the new interface. I'm working on testing different features in simulation, but they should probably also be tested on the robot before merging into master.

Some things I've already noticed:
- When the manipulation interface is selected, should the reach overlay circle disappear with the region outlines? Currently it does, but I can also keep it visible and just greyed out like the video feed.
- There is a lot of errors coming from the effort overlays. I think this is caused by references to non-existent region id's that were changed/removed in the split screen interface
- The whole interface feels a bit sluggish, I'm not sure if this is caused by the three.js rendering, or something else, but we may want to take a pass through and try to optimize things

**Comment by mayacakmak** [comment]
Excellent! I will  test this in that branch on the real robot before merging onto master. 

* I think it makes sense for it to disappear during manipulation mode. Let's keep it this way and see if situations come up where it would be good to have it during manipulation.
* Let me see about the sluggishness when I test on the robot.

- [ ] Yes, effort overlays are not fully working and you are completely right about the likely reason--feel free to fix this if you already know what to do, it's on my list of issues to address based on Vy and Elliston's tests. BTW we also need to find a way to visualize the feedback for the gripper effort, I was thinking either we change the button color towards red or we bring the gripper controls back onto the overlay (it's getting a bit crammed but Henry has not expressed any concerns about that)
- [ ] This makes me think we should have a checkbox in the settings for something like 'Visualize arm reach in navigation view' which can completely remove the visualization, so it is optional. It might be irrelevant for some tasks and the user should be able to disable it.

thanks!

**Comment by mayacakmak** [comment]
For some reason I'm unable to check out this branch as usual (perhaps something to do with the branch name starting with a "#"?) I'll go ahead and merge and test on master but let me know if you know why that might be @KaviMD, thanks!

**Pull request merged**
